; eASTROGAM_ANALYSISv31_all_remote.pro - Description
; ---------------------------------------------------------------------------------
; Processing the THELSIM eASTROGAM simulation:
; - Tracker
; - AC
; - Calorimeter
; ---------------------------------------------------------------------------------
; Output:
; - all files are created in a self-descripted subdirectory of the current directory. If the directory is not present it is created by the IDL script.
; ---------> FITS files
; - G4.RAW.eASTROGAM<version>.<phys>List.<sim_type>.<strip>.<point>.<n_in>ph.<energy>MeV.<theta>.<phi>.<file>.fits
; - L0.5.eASTROGAM<version>.<phys>List.<sim_type>.<strip>.<point>.<n_in>ph.<energy>MeV.<theta>.<phi>.<file>.fits
; - KALMAN.eASTROGAM<version>.<phys>List.<sim_type>.<strip>.<point>.<n_in>ph.<energy>MeV.<theta>.<phi>.<file>.fits
; - G4.AC.eASTROGAM<version>.<phys>List.<sim_type>.<strip>.<point>.<n_in>ph.<energy>MeV.<theta>.<phi>.<file>.fits
; - G4.CAL.eASTROGAM<version>.<phys>List.<sim_type>.<strip>.<point>.<n_in>ph.<energy>MeV.<theta>.<phi>.<file>.fits 
; ----------------------------------------------------------------------------------
; copyright            : (C) 2016 Valentina Fioretti
; email                : fioretti@iasfbo.inaf.it
; ----------------------------------------------
; Usage:
; eASTROGAM_ANALYSISv31_all
; ---------------------------------------------------------------------------------
; Notes:
; Each THELSIM FITS files individually processed
;  astrogam_version, $     ; % - Enter eASTROGAM release (e.g. V1.0):
;  bogemms_tag, $          ; % - Enter BoGEMMS release (e.g. 211):
;  sim_type, $             ; % - Enter simulation type [0 = Mono, 1 = Range, 2 = Chen, 3: Vela, 4: Crab, 4: G400]:
;  py_list, $              ; % - Enter the Physics List [0 = QGSP_BERT_EMV, 100 = ARGO, 300 = FERMI, 400 = ASTROMEV]:
;  N_in, $                 ; % - Enter the number of emitted particles:
;  part_type, $            ; % - Enter the particle type [ph = photons, mu = muons, g = geantino, p = proton, el = electron]:
;  n_files, $              ; % - Enter number of input files:
;  ene_range, $            ; % - Enter energy distribution [0 = MONO, 1 = POW, 2 = EXP, 3 = LIN]:
;  ene_min, $              ; % - Enter miminum energy [MeV]:
;  ene_max, $              ; % - Enter maximum energy [MeV]:
;  ang_type, $             ; % - Enter the angular distribution [e.g. UNI, ISO]:
;  theta_type, $           ; % - Enter theta:
;  phi_type, $             ; % - Enter phi:
;  pol_type, $             ; % - Is the source polarized? [0 = false, 1 = true]:
;  pol_angle, $            ; % - Enter Polarization angle:
;  source_g, $             ; % - Enter source geometry [0 = Point, 1 = Plane]:
;  isStrip, $              ; % - Strip/Pixels activated?:
;  repli, $                ; % - Strips/Pixels replicated?:
;  cal_flag, $             ; % - Is Cal present? [0 = false, 1 = true]:
;  ac_flag, $              ; % - Is AC present? [0 = false, 1 = true]:
;  passive_flag, $         ; % - Is Passive present? [0 = false, 1 = true]:
;  energy_thresh           ; % - Enter energy threshold [keV]:


.compile eASTROGAM_ANALYSISv31_all_remote
eASTROGAM_ANALYSISv31_all_remote, 'V1.1', '211', 0, 400, 10000, "ph", 4, 0, 5, 5, "UNI", 30, 225, 0, 20, 0, 1, 1, 0, 0, 0, 0
